# NYC TLC Gold Layer Analysis

Respuestas a las 20 preguntas usando las tablas `gold.*`.

Nombre: Matías Jaramillo
Clase: Data Mining
Tarea: PSet 02

In [1]:
import os
from pathlib import Path

import pandas as pd
import matplotlib.pyplot as plt
from sqlalchemy import create_engine, text

In [5]:
required_vars = [
    "POSTGRES_HOST",
    "POSTGRES_PORT",
    "POSTGRES_USER",
    "POSTGRES_PASSWORD",
    "POSTGRES_DB",
]

missing = [k for k in required_vars if not os.getenv(k)]

if missing:
    env_path = Path(".env")
    if env_path.exists():
        for line in env_path.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if key in required_vars and not os.getenv(key):
                os.environ[key] = value

missing = [k for k in required_vars if not os.getenv(k)]
if missing:
    raise ValueError(f"Missing required environment variables: {missing}")

DB_HOST = "localhost"
DB_PORT = os.getenv("POSTGRES_PORT")
DB_USER = os.getenv("POSTGRES_USER")
DB_PASSWORD = os.getenv("POSTGRES_PASSWORD")
DB_NAME = os.getenv("POSTGRES_DB")

print("Environment variables loaded successfully.")
print(f"POSTGRES_HOST={DB_HOST}")
print(f"POSTGRES_PORT={DB_PORT}")
print(f"POSTGRES_USER={DB_USER}")
print(f"POSTGRES_DB={DB_NAME}")

Environment variables loaded successfully.
POSTGRES_HOST=localhost
POSTGRES_PORT=5432
POSTGRES_USER=taxi_user
POSTGRES_DB=taxi_db

In [6]:
engine = create_engine(
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)

def run_query(sql: str) -> pd.DataFrame:
    return pd.read_sql(sql, engine)

In [7]:
run_query("""
SELECT 
    (SELECT COUNT(*) FROM gold.fct_trips) AS fct_rows,
    (SELECT COUNT(*) FROM gold.dim_zone) AS dim_zone_rows,
    (SELECT COUNT(*) FROM gold.dim_date) AS dim_date_rows,
    (SELECT COUNT(*) FROM gold.dim_service_type) AS dim_service_type_rows,
    (SELECT COUNT(*) FROM gold.dim_payment_type) AS dim_payment_type_rows,
    (SELECT COUNT(*) FROM gold.dim_vendor) AS dim_vendor_rows
""")

,fct_rows,dim_zone_rows,dim_date_rows,dim_service_type_rows,dim_payment_type_rows,dim_vendor_rows
0,162781997,265,1453,2,3,5

## 1. Trips por mes (2024)

**Tablas usadas:** `gold.fct_trips`

In [8]:
q1 = """
SELECT
    date_trunc('month', pickup_date)::date AS month,
    COUNT(*) AS trips
FROM gold.fct_trips
WHERE pickup_date >= DATE '2024-01-01'
  AND pickup_date < DATE '2025-01-01'
GROUP BY 1
ORDER BY 1;
"""
df1 = run_query(q1)
df1

         month    trips
0   2024-01-01  2966022
1   2024-02-01  3006887
2   2024-03-01  3573690
3   2024-04-01  3505040
4   2024-05-01  3712417
5   2024-06-01  3522221
6   2024-07-01  3059612
7   2024-08-01  2961613
8   2024-09-01  3613158
9   2024-10-01  3803439
10  2024-11-01  3618325
11  2024-12-01  3632908

**Interpretacion:** Se observa que en el año 2024 existen épocas de alta demanda en taxi trips. Estos meses son marzo-junio y luego regresa la temporada alta en septiembre hasta el fin de año.

## 2. Trips por service type y month

**Tablas usadas:** `gold.fct_trips`

In [9]:
q2 = """
SELECT
    date_trunc('month', pickup_date)::date AS month,
    service_type_key,
    COUNT(*) AS trips
FROM gold.fct_trips
WHERE pickup_date >= DATE '2024-01-01'
  AND pickup_date < DATE '2025-01-01'
GROUP BY 1, 2
ORDER BY 1, 2;
"""
df2 = run_query(q2)
df2

         month service_type_key    trips
0   2024-01-01            green    55931
1   2024-01-01           yellow  2910091
2   2024-02-01            green    52988
3   2024-02-01           yellow  2953899
4   2024-03-01            green    56762
5   2024-03-01           yellow  3516928
6   2024-04-01            green    55835
7   2024-04-01           yellow  3449205
8   2024-05-01            green    60288
9   2024-05-01           yellow  3652129
10  2024-06-01            green    54109
11  2024-06-01           yellow  3468112
12  2024-07-01            green    51132
13  2024-07-01           yellow  3008480
14  2024-08-01            green    51142
15  2024-08-01           yellow  2910471
16  2024-09-01            green    53757
17  2024-09-01           yellow  3559401
18  2024-10-01            green    55478
19  2024-10-01           yellow  3747961
20  2024-11-01            green    51601
21  2024-11-01           yellow  3566724
22  2024-12-01            green    53302
23  2024-12-01           yellow  3579606

**Interpretacion:** Se observa claramente que el tipo de trip con "yellow" service type contibuye en su mayoria al volumen de trips por mes. Lo cual indica que los trips "yellow" tienen mucha mas demanda o mucha mas oferta que los trips "green".

## 3. Top 10 pickup zones (total 2024)

**Tablas usadas:** `gold.fct_trips`, `gold.dim_zone`

In [10]:
q3 = """
SELECT
    z.zone,
    COUNT(*) AS trips
FROM gold.fct_trips f
JOIN gold.dim_zone z
  ON f.pu_zone_key = z.zone_key
WHERE f.pickup_date >= DATE '2024-01-01'
  AND f.pickup_date < DATE '2025-01-01'
GROUP BY z.zone
ORDER BY trips DESC
LIMIT 10;
"""
df3 = run_query(q3)
df3

                           zone    trips
0                   JFK Airport  1906407
1         Upper East Side South  1886927
2                Midtown Center  1881518
3         Upper East Side North  1713109
4                  Midtown East  1395526
5     Times Sq/Theatre District  1358260
6  Penn Station/Madison Sq West  1336366
7           Lincoln Square East  1295691
8             LaGuardia Airport  1272149
9                   Murray Hill  1157153

**Interpretacion:** Se pueden ver las top 10 zonas de pickup del 2024. Siendo la más popular JFK Airport y la menos popular del top 10 Murray Hill.

## 4. Top 10 dropoff zones (total 2024)

**Tablas usadas:** `gold.fct_trips`, `gold.dim_zone`

In [11]:
q4 = """
SELECT
    z.zone,
    COUNT(*) AS trips
FROM gold.fct_trips f
JOIN gold.dim_zone z
  ON f.do_zone_key = z.zone_key
WHERE f.pickup_date >= DATE '2024-01-01'
  AND f.pickup_date < DATE '2025-01-01'
GROUP BY z.zone
ORDER BY trips DESC
LIMIT 10;
"""
df4 = run_query(q4)
df4

                        zone    trips
0      Upper East Side North  1805768
1      Upper East Side South  1712820
2             Midtown Center  1519454
3  Times Sq/Theatre District  1284610
4                Murray Hill  1198013
5               Midtown East  1169673
6        Lincoln Square East  1135883
7      Upper West Side South  1134225
8               East Chelsea  1062171
9            Lenox Hill West  1056920

**Interpretacion:** Aquí se puede ver el top 10 de los dropoff zones del 2024. La más popular siendo Upper East Side North y la menos popular del top 10 siendo Lenox Hill West.

## 5. Top 5 boroughs por month (pickup)

**Tablas usadas:** `gold.fct_trips`, `gold.dim_zone`

In [12]:
q5 = """
WITH ranked AS (
    SELECT
        date_trunc('month', f.pickup_date)::date AS month,
        z.borough,
        COUNT(*) AS trips,
        ROW_NUMBER() OVER (
            PARTITION BY date_trunc('month', f.pickup_date)::date
            ORDER BY COUNT(*) DESC
        ) AS rn
    FROM gold.fct_trips f
    JOIN gold.dim_zone z
      ON f.pu_zone_key = z.zone_key
    WHERE f.pickup_date >= DATE '2024-01-01'
      AND f.pickup_date < DATE '2025-01-01'
    GROUP BY 1, 2
)
SELECT month, borough, trips
FROM ranked
WHERE rn <= 5
ORDER BY month, trips DESC;
"""
df5 = run_query(q5)
df5

         month    borough    trips
0   2024-01-01  Manhattan  2643139
1   2024-01-01     Queens   280753
2   2024-01-01   Brooklyn    32575
3   2024-01-01      Bronx     7690
4   2024-01-01        NaN     1517
5   2024-02-01  Manhattan  2705433
6   2024-02-01     Queens   256948
7   2024-02-01   Brooklyn    35194
8   2024-02-01      Bronx     7610
9   2024-02-01        NaN     1378
10  2024-03-01  Manhattan  3187267
11  2024-03-01     Queens   320727
12  2024-03-01   Brooklyn    51650
13  2024-03-01      Bronx    11746
14  2024-03-01        NaN     1862
15  2024-04-01  Manhattan  3117117
16  2024-04-01     Queens   321574
17  2024-04-01   Brooklyn    52503
18  2024-04-01      Bronx    11441
19  2024-04-01        NaN     1814
20  2024-05-01  Manhattan  3282896
21  2024-05-01     Queens   352264
22  2024-05-01   Brooklyn    61828
23  2024-05-01      Bronx    12644
24  2024-05-01        NaN     2045
25  2024-06-01  Manhattan  3111320
26  2024-06-01     Queens   332053
27  2024-06-01   Brooklyn    64459
28  2024-06-01      Bronx    11861
29  2024-06-01        NaN     1919
30  2024-07-01  Manhattan  2664201
31  2024-07-01     Queens   330469
32  2024-07-01   Brooklyn    51972
33  2024-07-01      Bronx    10296
34  2024-07-01        NaN     2011
35  2024-08-01  Manhattan  2556344
36  2024-08-01     Queens   338515
37  2024-08-01   Brooklyn    53371
38  2024-08-01      Bronx    10662
39  2024-08-01        NaN     2005
40  2024-09-01  Manhattan  3160265
41  2024-09-01     Queens   364988
42  2024-09-01   Brooklyn    72316
43  2024-09-01      Bronx    12687
44  2024-09-01        NaN     2162
45  2024-10-01  Manhattan  3353104
46  2024-10-01     Queens   368077
47  2024-10-01   Brooklyn    66921
48  2024-10-01      Bronx    12449
49  2024-10-01        NaN     2140
50  2024-11-01  Manhattan  3206573
51  2024-11-01     Queens   323477
52  2024-11-01   Brooklyn    72862
53  2024-11-01      Bronx    13005
54  2024-11-01        NaN     1672
55  2024-12-01  Manhattan  3219494
56  2024-12-01     Queens   330867
57  2024-12-01   Brooklyn    68039
58  2024-12-01      Bronx    11699
59  2024-12-01        NaN     2022

**Interpretacion:** Se observan los top borough pickups por mes. Esto nos ayuda a identificar tendencias geograficas. En este caso se puede ver que siempre la mayoria de pickups se realizan en Manhattan, seguido por Queens, luego Brooklyn, Bronx y finalmente los boroughs no definidos. Este patron se repite en todos los meses del 2024.

## 6. Horas pico (top 5 horas) para cada dia de la semana

**Tablas usadas:** `gold.fct_trips`, `gold.dim_date`

In [13]:
q6 = """
WITH hourly AS (
    SELECT
        d.day_name,
        EXTRACT(HOUR FROM f.pickup_ts)::int AS pickup_hour,
        COUNT(*) AS trips,
        ROW_NUMBER() OVER (
            PARTITION BY d.day_name
            ORDER BY COUNT(*) DESC
        ) AS rn
    FROM gold.fct_trips f
    JOIN gold.dim_date d
      ON f.pickup_date_key = d.date_key
    GROUP BY 1, 2
)
SELECT day_name, pickup_hour, trips
FROM hourly
WHERE rn <= 5
ORDER BY day_name, trips DESC;
"""
df6 = run_query(q6)
df6

     day_name  pickup_hour    trips
0      Friday           18  1778470
1      Friday           17  1649347
2      Friday           19  1640122
3      Friday           15  1487237
4      Friday           16  1478700
5      Monday           18  1490014
6      Monday           17  1461493
7      Monday           15  1337370
8      Monday           16  1328903
9      Monday           14  1279533
10   Saturday           18  1587942
11   Saturday           19  1549472
12   Saturday           17  1526817
13   Saturday           16  1459926
14   Saturday           22  1415704
15     Sunday           14  1295115
16     Sunday           17  1291153
17     Sunday           16  1277240
18     Sunday           18  1260647
19     Sunday           15  1258416
20   Thursday           18  1884286
21   Thursday           17  1751539
22   Thursday           19  1652215
23   Thursday           21  1567633
24   Thursday           16  1539817
25    Tuesday           18  1763746
26    Tuesday           17  1653614
27    Tuesday           19  1493614
28    Tuesday           21  1459291
29    Tuesday           16  1456670
30  Wednesday           18  1837798
31  Wednesday           17  1717322
32  Wednesday           19  1616746
33  Wednesday           21  1545111
34  Wednesday           16  1501666

**Interpretacion:** Se observa las horas más ocupadas para taxi trips. Se puede identificar una tendencia que todos los dias exceptuando domingo, la hora mas en demanda son las 5PM, la cual tiene sentido debido a que es la hora cuando muchas personas salen del trabajo.

## 7. Distribucion de viajes por dia de la semana (ranking)

**Tablas usadas:** `gold.fct_trips`, `gold.dim_date`

In [14]:
q7 = """
SELECT
    d.day_name,
    COUNT(*) AS trips
FROM gold.fct_trips f
JOIN gold.dim_date d
  ON f.pickup_date_key = d.date_key
GROUP BY d.day_name
ORDER BY trips DESC;
"""
df7 = run_query(q7)
df7

    day_name     trips
0   Thursday  25350794
1  Wednesday  24469328
2     Friday  24411970
3   Saturday  24395224
4    Tuesday  23222066
5     Sunday  20688650
6     Monday  20243965

**Interpretacion:** Ranking de los dias más transitados. Donde los dias jueves son los dias con más demanda y los dias lunes los que tienen menos demanda.

## 8. Ingresos total por mes

**Tablas usadas:** `gold.fct_trips`

In [15]:
q8 = """
SELECT
    date_trunc('month', pickup_date)::date AS month,
    SUM(total_amount) AS total_revenue
FROM gold.fct_trips
GROUP BY 1
ORDER BY 1;
"""
df8 = run_query(q8)
df8

         month  total_revenue
0   2001-01-01   3.541500e+02
1   2001-08-01   2.455000e+01
2   2002-10-01   1.141846e+04
3   2002-12-01   1.011180e+03
4   2003-01-01   6.052100e+02
5   2007-12-01   2.275000e+01
6   2008-12-01   3.342790e+03
7   2009-01-01   2.287130e+03
8   2012-02-01   0.000000e+00
9   2014-11-01   5.238000e+01
10  2021-12-01   4.880600e+02
11  2022-01-01   4.768427e+07
12  2022-02-01   5.859483e+07
13  2022-03-01   7.505376e+07
14  2022-04-01   7.658668e+07
15  2022-05-01   7.953378e+07
16  2022-06-01   7.904123e+07
17  2022-07-01   6.819238e+07
18  2022-08-01   6.806149e+07
19  2022-09-01   7.224908e+07
20  2022-10-01   8.166421e+07
21  2022-11-01   7.154866e+07
22  2022-12-01   8.342891e+07
23  2023-01-01   8.317779e+07
24  2023-02-01   7.897958e+07
25  2023-03-01   9.580678e+07
26  2023-04-01   9.400258e+07
27  2023-05-01   1.028652e+08
28  2023-06-01   9.733375e+07
29  2023-07-01   8.429337e+07
30  2023-08-01   8.222159e+07
31  2023-09-01   8.625069e+07
32  2023-10-01   1.041677e+08
33  2023-11-01   9.723255e+07
34  2023-12-01   9.823842e+07
35  2024-01-01   8.103653e+07
36  2024-02-01   8.168968e+07
37  2024-03-01   9.901064e+07
38  2024-04-01   9.849976e+07
39  2024-05-01   1.077897e+08
40  2024-06-01   1.008951e+08
41  2024-07-01   8.861629e+07
42  2024-08-01   8.665960e+07
43  2024-09-01   1.062185e+08
44  2024-10-01   1.113579e+08
45  2024-11-01   1.032211e+08
46  2024-12-01   1.066268e+08
47  2025-01-01   9.130973e+07
48  2025-02-01   9.172893e+07
49  2025-03-01   1.116275e+08
50  2025-04-01   1.085776e+08
51  2025-05-01   1.268978e+08
52  2025-06-01   1.214917e+08
53  2025-07-01   1.078637e+08
54  2025-08-01   9.775843e+07
55  2025-09-01   1.212686e+08
56  2025-10-01   1.226006e+08
57  2025-11-01   1.096765e+08
58  2025-12-01   2.943500e+02
59  2026-06-01   7.307000e+01

**Interpretacion:** Se pueden observar tendencias en los ingresos a traves de los años. Se relaciona con la anterior pregunta de numero de trips por mes, porque se pueden observar tendencias similares como las épocas de mayor demanda.

## 9. Ingreso total por service type y por mes

**Tablas usadas:** `gold.fct_trips`

In [16]:
q9 = """
SELECT
    date_trunc('month', pickup_date)::date AS month,
    service_type_key,
    SUM(total_amount) AS total_revenue
FROM gold.fct_trips
GROUP BY 1, 2
ORDER BY 1, 2;
"""
df9 = run_query(q9)
df9

          month service_type_key  total_revenue
0    2001-01-01           yellow   3.541500e+02
1    2001-08-01           yellow   2.455000e+01
2    2002-10-01           yellow   1.141846e+04
3    2002-12-01           yellow   1.011180e+03
4    2003-01-01           yellow   6.052100e+02
..          ...              ...            ...
105  2025-10-01           yellow   1.213315e+08
106  2025-11-01            green   1.169418e+06
107  2025-11-01           yellow   1.085070e+08
108  2025-12-01            green   2.943500e+02
109  2026-06-01           yellow   7.307000e+01

[110 rows x 3 columns]

**Interpretacion:** Similar a la pregunta anterior, nos indica tendencias en el tiempo sobre la demanda por cada service type, solo que tambien nos indica la diferencia entre los ingresos de los trips "yellow" y los trips "green".

## 10. Tip promedio por mes

**Tablas usadas:** `gold.fct_trips`

In [17]:
q10 = """
SELECT
    date_trunc('month', pickup_date)::date AS month,
    AVG(tip_amount / NULLIF(fare_amount, 0)) AS avg_tip_pct
FROM gold.fct_trips
GROUP BY 1
ORDER BY 1;
"""
df10 = run_query(q10)
df10

         month  avg_tip_pct
0   2001-01-01     0.021665
1   2001-08-01     0.000000
2   2002-10-01     0.076697
3   2002-12-01     0.111385
4   2003-01-01     0.059114
5   2007-12-01     0.000000
6   2008-12-01     0.147055
7   2009-01-01     0.125709
8   2012-02-01          NaN
9   2014-11-01     0.263746
10  2021-12-01     0.197885
11  2022-01-01     0.230401
12  2022-02-01     0.218334
13  2022-03-01     0.217885
14  2022-04-01     0.226465
15  2022-05-01     0.214791
16  2022-06-01     0.225539
17  2022-07-01     0.214210
18  2022-08-01     0.238135
19  2022-09-01     0.216307
20  2022-10-01     0.238098
21  2022-11-01     0.218933
22  2022-12-01     0.230070
23  2023-01-01     0.211208
24  2023-02-01     0.211418
25  2023-03-01     0.218558
26  2023-04-01     0.230003
27  2023-05-01     0.219036
28  2023-06-01     0.232821
29  2023-07-01     0.238139
30  2023-08-01     0.214159
31  2023-09-01     0.205921
32  2023-10-01     0.215063
33  2023-11-01     0.219432
34  2023-12-01     0.215740
35  2024-01-01     0.229593
36  2024-02-01     0.208898
37  2024-03-01     0.195514
38  2024-04-01     0.199689
39  2024-05-01     0.200958
40  2024-06-01     0.190780
41  2024-07-01     0.193649
42  2024-08-01     0.187778
43  2024-09-01     0.188163
44  2024-10-01     0.195785
45  2024-11-01     0.210756
46  2024-12-01     0.197286
47  2025-01-01     0.194831
48  2025-02-01     0.183890
49  2025-03-01     0.177709
50  2025-04-01     0.185729
51  2025-05-01     0.176282
52  2025-06-01     0.177803
53  2025-07-01     0.165186
54  2025-08-01     0.161428
55  2025-09-01     0.176787
56  2025-10-01     0.175592
57  2025-11-01     0.170396
58  2025-12-01     0.187601
59  2026-06-01     0.288626

**Interpretacion:** Se muestra el porcentaje del fare que se recibe como tip. Se pueden observar las tendencias de tip a lo largo del tiempo.Se puede observar que el tip no cambia mucho, unicamente se puede ver que antes era mas en un 20% y en tiempos más recientes ha bajado a un 19% - 18%.

## 11. Tip % bpory borough y mes

**Tablas usadas:** `gold.fct_trips`, `gold.dim_zone`

In [18]:
q11 = """
SELECT
    date_trunc('month', f.pickup_date)::date AS month,
    z.borough,
    AVG(f.tip_amount / NULLIF(f.fare_amount, 0)) AS avg_tip_pct
FROM gold.fct_trips f
JOIN gold.dim_zone z
  ON f.pu_zone_key = z.zone_key
GROUP BY 1, 2
ORDER BY 1, 2;
"""
df11 = run_query(q11)
df11

          month        borough  avg_tip_pct
0    2001-01-01      Manhattan     0.027855
1    2001-01-01         Queens     0.000000
2    2001-08-01         Queens     0.000000
3    2002-10-01          Bronx     0.000000
4    2002-10-01       Brooklyn     0.008242
..          ...            ...          ...
351  2025-11-01         Queens     0.139789
352  2025-11-01  Staten Island     0.080210
353  2025-11-01            NaN     0.165480
354  2025-12-01      Manhattan     0.187601
355  2026-06-01         Queens     0.288626

[356 rows x 3 columns]

**Interpretacion:** Aqui se puede observar la tendencia del tip a lo largo del tiempo y categorizado por borough. De esta manera se puede identificar flujos en tips  y el efecto que tiene el borough en la variable igualmente.

## 12. Top 10 pickup zones por ingreso total.

**Tablas usadas:** `gold.fct_trips`, `gold.dim_zone`

In [19]:
q12 = """
SELECT
    z.zone,
    SUM(f.total_amount) AS total_revenue
FROM gold.fct_trips f
JOIN gold.dim_zone z
  ON f.pu_zone_key = z.zone_key
GROUP BY z.zone
ORDER BY total_revenue DESC
LIMIT 10;
"""
df12 = run_query(q12)
df12

                           zone  total_revenue
0                   JFK Airport   5.742785e+08
1             LaGuardia Airport   3.038308e+08
2                Midtown Center   1.692282e+08
3         Upper East Side South   1.450595e+08
4     Times Sq/Theatre District   1.398398e+08
5         Upper East Side North   1.328292e+08
6  Penn Station/Madison Sq West   1.260662e+08
7                  Midtown East   1.240145e+08
8           Lincoln Square East   1.063228e+08
9                 Midtown North   1.057795e+08

**Interpretacion:** Se observan las top 10 pickup zones rankeadas por ingreso total. De esta manera se puede identificar que los trips más valiosos son los que tienen pickup en JFK Airport.

## 13. Top 10 pickup zones por tip % con minimo N trips

**Tablas usadas:** `gold.fct_trips`, `gold.dim_zone`

**N:** 1,000 trips

In [20]:
q13 = """
SELECT
    z.zone,
    COUNT(*) AS trips,
    AVG(f.tip_amount / NULLIF(f.fare_amount, 0)) AS avg_tip_pct
FROM gold.fct_trips f
JOIN gold.dim_zone z
  ON f.pu_zone_key = z.zone_key
GROUP BY z.zone
HAVING COUNT(*) >= 1000
ORDER BY avg_tip_pct DESC
LIMIT 10;
"""
df13 = run_query(q13)
df13

                              zone   trips  avg_tip_pct
0                   Outside of NYC  140776     5.758538
1                   Newark Airport   24434     4.099271
2                  Cambria Heights    8987     1.521469
3          Bay Terrace/Fort Totten    3349     1.075968
4                     Baisley Park   62768     0.829308
5                     Astoria Park    1281     0.734793
6       Spuyten Duyvil/Kingsbridge   14891     0.680902
7                          Belmont    9491     0.654706
8                    East New York   83440     0.609023
9  Marine Park/Floyd Bennett Field    2259     0.548981

**Interpretacion:** Usar un minimo N, nos ayuda a no listar zonas con pocos viajes y altos tips, para excluir datos atípicos. Se puede ver que la zona con tips consistentes mas altos es Outside of NYC.

## 14. Cash vs card: trips, ingreso, tip %

**Tablas usadas:** `gold.fct_trips`

In [21]:
q14 = """
SELECT
    payment_type_key,
    COUNT(*) AS trips,
    SUM(total_amount) AS total_revenue,
    AVG(tip_amount / NULLIF(fare_amount, 0)) AS avg_tip_pct
FROM gold.fct_trips
WHERE payment_type_key IN ('cash', 'card')
GROUP BY payment_type_key
ORDER BY trips DESC;
"""
df14 = run_query(q14)
df14

  payment_type_key      trips  total_revenue  avg_tip_pct
0             card  119535232   3.342808e+09     0.271517
1             cash   24004207   5.478649e+08     0.000020

**Interpretacion:** Se compara los metodos de pago para identificar patrones en los pagos. Se puede ver que pagos con tarjeta son mushisimos más que con cash, igualmente generan mucho más ingreso y suelen dejar mayor porcentaje de tip que cuando el metodo de pago es en cash.

## 15. Duracion promedio de trip (minutos) por mes

**Tablas usadas:** `gold.fct_trips`

In [22]:
q15 = """
SELECT
    date_trunc('month', pickup_date)::date AS month,
    AVG(trip_duration_minutes) AS avg_duration_minutes
FROM gold.fct_trips
GROUP BY 1
ORDER BY 1;
"""
df15 = run_query(q15)
df15

         month  avg_duration_minutes
0   2001-01-01          3.691241e+02
1   2001-08-01          2.243333e+01
2   2002-10-01          3.101679e+06
3   2002-12-01          5.019576e+02
4   2003-01-01          3.277250e+02
5   2007-12-01          1.700000e+01
6   2008-12-01          7.410979e+02
7   2009-01-01          4.417496e+02
8   2012-02-01          1.432217e+03
9   2014-11-01          4.274833e+02
10  2021-12-01          6.181667e+01
11  2022-01-01          1.434346e+01
12  2022-02-01          1.577752e+01
13  2022-03-01          1.641389e+01
14  2022-04-01          1.737662e+01
15  2022-05-01          1.828183e+01
16  2022-06-01          1.816053e+01
17  2022-07-01          1.688133e+01
18  2022-08-01          1.704607e+01
19  2022-09-01          1.876636e+01
20  2022-10-01          1.808609e+01
21  2022-11-01          1.819425e+01
22  2022-12-01          1.835544e+01
23  2023-01-01          1.572190e+01
24  2023-02-01          1.607458e+01
25  2023-03-01          1.696451e+01
26  2023-04-01          1.731106e+01
27  2023-05-01          1.816392e+01
28  2023-06-01          1.780209e+01
29  2023-07-01          1.718570e+01
30  2023-08-01          1.723744e+01
31  2023-09-01          1.888264e+01
32  2023-10-01          1.839278e+01
33  2023-11-01          1.825830e+01
34  2023-12-01          1.825334e+01
35  2024-01-01          1.571527e+01
36  2024-02-01          1.607013e+01
37  2024-03-01          1.673804e+01
38  2024-04-01          1.711485e+01
39  2024-05-01          1.811266e+01
40  2024-06-01          1.765229e+01
41  2024-07-01          1.729448e+01
42  2024-08-01          1.745987e+01
43  2024-09-01          1.869895e+01
44  2024-10-01          1.831310e+01
45  2024-11-01          1.790635e+01
46  2024-12-01          1.877390e+01
47  2025-01-01          1.513263e+01
48  2025-02-01          1.550302e+01
49  2025-03-01          1.607531e+01
50  2025-04-01          1.672128e+01
51  2025-05-01          1.795451e+01
52  2025-06-01          1.745947e+01
53  2025-07-01          1.717667e+01
54  2025-08-01          1.734515e+01
55  2025-09-01          1.865433e+01
56  2025-10-01          1.867723e+01
57  2025-11-01          1.837202e+01
58  2025-12-01          1.571154e+01
59  2026-06-01          2.093333e+01

**Interpretacion:** Se puede observar patrones de duracion de trip. Lo cual nos puede indicar condiciones de trafico o eventos que pudieron alentar trips en diferentes meses.

## 16. Distancia promedio por mes

**Tablas usadas:** `gold.fct_trips`

In [23]:
q16 = """
SELECT
    date_trunc('month', pickup_date)::date AS month,
    AVG(trip_distance) AS avg_trip_distance
FROM gold.fct_trips
GROUP BY 1
ORDER BY 1;
"""
df16 = run_query(q16)
df16

         month  avg_trip_distance
0   2001-01-01           8.395556
1   2001-08-01           7.080000
2   2002-10-01           3.782980
3   2002-12-01           8.538182
4   2003-01-01          12.159167
5   2007-12-01           3.000000
6   2008-12-01           8.512083
7   2009-01-01           4.351829
8   2012-02-01           0.000000
9   2014-11-01           6.430000
10  2021-12-01           3.375926
11  2022-01-01           7.221725
12  2022-02-01           7.984493
13  2022-03-01           7.108222
14  2022-04-01           7.442083
15  2022-05-01           9.259059
16  2022-06-01           8.038747
17  2022-07-01           7.468874
18  2022-08-01           6.753550
19  2022-09-01           9.089672
20  2022-10-01           7.828638
21  2022-11-01           7.798408
22  2022-12-01           5.410373
23  2023-01-01           3.904611
24  2023-02-01           4.059366
25  2023-03-01           4.094003
26  2023-04-01           4.290293
27  2023-05-01           4.649421
28  2023-06-01           4.752789
29  2023-07-01           4.905434
30  2023-08-01           5.292462
31  2023-09-01           4.763879
32  2023-10-01           4.316472
33  2023-11-01           3.934001
34  2023-12-01           4.097319
35  2024-01-01           4.196498
36  2024-02-01           4.122956
37  2024-03-01           4.687339
38  2024-04-01           5.431942
39  2024-05-01           5.559349
40  2024-06-01           5.372558
41  2024-07-01           5.249676
42  2024-08-01           5.205220
43  2024-09-01           5.976761
44  2024-10-01           5.245142
45  2024-11-01           5.682296
46  2024-12-01           5.254004
47  2025-01-01           6.107124
48  2025-02-01           6.199315
49  2025-03-01           6.732100
50  2025-04-01           7.205245
51  2025-05-01           7.771914
52  2025-06-01           7.581147
53  2025-07-01           7.354551
54  2025-08-01           7.173225
55  2025-09-01           7.061244
56  2025-10-01           6.694266
57  2025-11-01           6.622503
58  2025-12-01           2.344615
59  2026-06-01          10.960000

**Interpretacion:** Se pueden observar las tendencias en la distancia de los trips por mes. Esto puede ayudar a comprender patrones sobre el comportamiento dde los clientes al usar un taxi. Se usan mayormente para viajes cortos o largos?

## 17. Velocidad promedio (mph) por borough y franja horaria

**Tablas usadas:** `gold.fct_trips`, `gold.dim_zone`

In [24]:
q17 = """
SELECT
    z.borough,
    CASE
        WHEN EXTRACT(HOUR FROM f.pickup_ts) BETWEEN 6 AND 11 THEN 'morning'
        WHEN EXTRACT(HOUR FROM f.pickup_ts) BETWEEN 12 AND 17 THEN 'afternoon'
        WHEN EXTRACT(HOUR FROM f.pickup_ts) BETWEEN 18 AND 23 THEN 'evening'
        ELSE 'night'
    END AS time_band,
    AVG(f.trip_distance / NULLIF(f.trip_duration_minutes / 60.0, 0)) AS avg_mph
FROM gold.fct_trips f
JOIN gold.dim_zone z
  ON f.pu_zone_key = z.zone_key
GROUP BY 1, 2
ORDER BY 1, 2;
"""
df17 = run_query(q17)
df17

          borough  time_band     avg_mph
0           Bronx  afternoon  180.152577
1           Bronx    evening  168.140578
2           Bronx    morning  201.299619
3           Bronx      night   94.409876
4        Brooklyn  afternoon   90.880735
5        Brooklyn    evening   70.642798
6        Brooklyn    morning  144.939079
7        Brooklyn      night   80.414735
8             EWR  afternoon   67.767989
9             EWR    evening   60.300375
10            EWR    morning  101.002844
11            EWR      night   40.627377
12      Manhattan  afternoon   15.050741
13      Manhattan    evening   16.868629
14      Manhattan    morning   24.481215
15      Manhattan      night   34.692329
16         Queens  afternoon   37.176168
17         Queens    evening   35.177829
18         Queens    morning   52.575842
19         Queens      night   51.085871
20  Staten Island  afternoon   87.240912
21  Staten Island    evening   27.647233
22  Staten Island    morning  170.654171
23  Staten Island      night   38.584159
24            NaN  afternoon  358.514747
25            NaN    evening  352.913361
26            NaN    morning  506.755587
27            NaN      night  246.092232

**Interpretacion:** Se puede observar la velocidad promedio del trip con su respectivo borough y franja horaria. Con esta data se puede aprender sobre los patrones de congestion en diferentes fanjas horarias y categorizadas por borough, lo cual puede luego ayudar a opeaciones logisticas para cumplir con la demanda.

## 18. Percentiles p50 y p90 de duracion por borough

**Tablas usadas:** `gold.fct_trips`, `gold.dim_zone`

In [25]:
q18 = """
SELECT
    z.borough,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY f.trip_duration_minutes) AS p50_duration,
    percentile_cont(0.9) WITHIN GROUP (ORDER BY f.trip_duration_minutes) AS p90_duration
FROM gold.fct_trips f
JOIN gold.dim_zone z
  ON f.pu_zone_key = z.zone_key
GROUP BY z.borough
ORDER BY z.borough;
"""
df18 = run_query(q18)
df18

         borough  p50_duration  p90_duration
0          Bronx     23.183333     61.483333
1       Brooklyn     21.533333     48.550000
2            EWR      0.150000      1.366667
3      Manhattan     11.883333     26.300000
4         Queens     31.916667     60.766667
5  Staten Island     29.450000     72.820000
6            NaN      0.800000     60.266667

**Interpretacion:** p50 indica duracion normal mientras que p90 indica duraciones largas. De esta manera se puede comparar lo "normal" y lo "demorado" categorizado por borough.

## 19. Top 10 pickup zones por duracion p90

**Tablas usadas:** `gold.fct_trips`, `gold.dim_zone`

In [26]:
q19 = """
SELECT
    z.zone,
    percentile_cont(0.9) WITHIN GROUP (ORDER BY f.trip_duration_minutes) AS p90_duration
FROM gold.fct_trips f
JOIN gold.dim_zone z
  ON f.pu_zone_key = z.zone_key
GROUP BY z.zone
ORDER BY p90_duration DESC
LIMIT 10;
"""
df19 = run_query(q19)
df19

                                zone  p90_duration
0                      Arden Heights    124.086667
1                    Freshkills Park    102.086667
2                       Far Rockaway    100.010000
3                    Hammels/Arverne     97.335000
4                       Coney Island     92.698333
5  Eltingville/Annadale/Prince's Bay     90.876667
6                      Rockaway Park     88.230000
7                     Brighton Beach     84.110000
8                          Gravesend     83.266667
9                    Cambria Heights     80.893333

**Interpretacion:** Se observan las zonas con el p90 mas alto (top 10). Son indicadores de los viajes mas largos. Esto puede indicar zonas donde es mas probable que haya congestion o demoras.

## 20. Top 10 borough-to-borough rutas por trip count

**Tablas usadas:** `gold.fct_trips`, `gold.dim_zone`

In [27]:
q20 = """
SELECT
    pu.borough AS pickup_borough,
    do_.borough AS dropoff_borough,
    COUNT(*) AS trips
FROM gold.fct_trips f
JOIN gold.dim_zone pu
  ON f.pu_zone_key = pu.zone_key
JOIN gold.dim_zone do_
  ON f.do_zone_key = do_.zone_key
GROUP BY pu.borough, do_.borough
ORDER BY trips DESC
LIMIT 10;
"""
df20 = run_query(q20)
df20

  pickup_borough dropoff_borough      trips
0      Manhattan       Manhattan  133950293
1         Queens       Manhattan    8271652
2      Manhattan          Queens    4707004
3         Queens          Queens    4283676
4      Manhattan        Brooklyn    3369054
5         Queens        Brooklyn    2265680
6       Brooklyn        Brooklyn    1754410
7       Brooklyn       Manhattan     971431
8      Manhattan           Bronx     638249
9         Queens             NaN     402625

**Interpretacion:** Se muestran los top 10 viajes entre boroughs. Esto nos puede dar evidencias de patrones y flujo de movimiento en la ciudad. Por ejemplo, en este caso se observa que la ruta mas popular es movimientos que se mantienen dentro de Manhattan.